const data=[
["I Year I Semester",[["MA101BS","Matrices and Calculus",4],["CH102BS","Engineering Chemistry",4],["CS103ES","Programming for Problem Solving",3],["EE104ES","Basic Electrical Engineering",2],["ME105ES","Computer Aided Engineering Graphics",3],["CS106ES","Elements of Computer Science & Engineering",1],["CH107BS","Engineering Chemistry Laboratory",1],["CS108ES","Programming for Problem Solving Laboratory",1],["EE109ES","Basic Electrical Engineering Laboratory",1]]],
["I Year II Semester",[["MA201BS","Ordinary Differential Equations and Vector Calculus",4],["PH202BS","Applied Physics",4],["ME203ES","Engineering Workshop",2.5],["EN204HS","English for Skill Enhancement",2],["EC205ES","Electronic Devices and Circuits",2],["CS206PC","Python Programming Laboratory",2],["PH207BS","Applied Physics Laboratory",1.5],["EN208HS","English Language and Communication Skills Laboratory",1],["CS209ES","IT Workshop",1]]],
["II Year I Semester",[["CS301PC","Digital Electronics",3],["CS302PC","Data Structures",3],["CS303PC","Computer Oriented Statistical Methods",4],["CS304PC","Computer Organization and Architecture",3],["CS305PC","Object Oriented Programming through Java",3],["CS306PC","Data Structures Lab",1.5],["CS307PC","Object Oriented Programming through Java Lab",1.5],["CS308PC","Data Visualization – R Programming / Power BI",1]]],
["II Year II Semester",[["CS401PC","Discrete Mathematics",3],["SM402MS","Business Economics & Financial Analysis",3],["CS403PC","Operating Systems",3],["CS404PC","Database Management Systems",3],["CS405PC","Software Engineering",3],["CS406PC","Operating Systems Lab",1],["CS407PC","DBMS Lab",1],["CS408PC","Applied Software Project",2],["CS409PC","Full Stack Development",1]]],
["III Year I Semester",[["CS501PC","Design and Analysis of Algorithms",4],["CS502PC","Computer Networks",3],["CS503PC","DevOps & Cloud",3],["CS601PC","Machine Learning",3],["CS510PC","Prompt Engineering & AI-Assisted Development",1],["PE-I","Professional Elective I",3],["CS506PC","UI Design – Flutter",1],["EN508HS","Advanced English Communication Skills Lab",1],["CS507PC","Software Testing",1]]],
["III Year II Semester",[["CS602PC","Formal Languages and Automata Theory",3],["CS603PC","Artificial Intelligence",3],["CS610PC","Deep Learning",4],["CS611PC","Deep Learning Lab",1],["CS612PC","Natural Language Processing",3],["PE-II","Professional Elective II",3],["CS606PC","Industrial Project / Internship",2],["CS609PC","AI/ML Engineering Practice",1]]],
["IV Year I Semester",[["CS701PC","Cryptography and Network Security",3],["CS702PC","Compiler Design",3],["CS710PC","Cyber Security",3],["CS711PC","Cyber Security Lab",1],["CS720PC","Generative AI & LLM Applications",3],["CS721PC","Cloud-Native & Distributed Systems",3],["PE-III","Professional Elective III",1],["CS705PC","Project Stage-I",3]]],
["IV Year II Semester",[["CS801PC","Organizational Behavior",3],["PE-IV","Professional Elective IV",3],["OE-I","Open Elective I",3],["CS810PC","Software Testing / Secure Software Engineering Practice",3],["CS811PC","Project Stage-II & Seminar",8]]]
];
const f=document.getElementById("filter"),g=document.getElementById("grid"),c=document.getElementById("credits");
data.forEach((x,i)=>f.insertAdjacentHTML("beforeend",`<option value="${i}">${x[0]}</option>`));
function render(){let a=f.value==="all"?data:[data[+f.value]];g.innerHTML='<div class="semestergrid">'+a.map(x=>{let t=x[1].reduce((s,q)=>s+q[2],0);return `<article class="semester"><h3>${x[0]}</h3><b>Credits: ${t}</b>${x[1].map(q=>`<div class="course"><span>${q[1]}<span class="code">${q[0]}</span></span><b>${q[2]}</b></div>`).join("")}</article>`}).join("")+'</div>';c.textContent=f.value==="all"?160:a[0][1].reduce((s,q)=>s+q[2],0)}
f.addEventListener("change",render);render();